version: "3"
services:
    etcd:
        image: bitnami/etcd:latest
        environment:
            - TZ=Asia/Shanghai
            - LANG=en_US.UTF-8
            - ALLOW_NONE_AUTHENTICATION=yes
            - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
        volumes:
            - ./etcd_data:/bitnami/etcd
        ports:
            - 2379:2379
            - 2380:2380