version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd  -broadcast-address=127.0.0.1  --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"



#version: '3'
#services:
#  nsqlookupd:
#    image: nsqio/nsq
#    command: /nsqlookupd --broadcast-address=192.168.10.234 --tcp-address=:41600 --http-address=:41610
#    ports:
#      - "41600:41600"
#      - "41610:41610"
#  nsqd:
#    image: nsqio/nsq
#    command: /nsqd --broadcast-address=192.168.10.234 --tcp-address=:41500 --http-address=:41510  --lookupd-tcp-address=nsqlookupd:41600 --lookupd-tcp-address=nsqlookupd:41610
#    depends_on:
#      - nsqlookupd
#    ports:
#      - "41500:41500"
#      - "41510:41510"
#  nsqadmin:
#    image: nsqio/nsq
#    command: /nsqadmin --lookupd-http-address=192.168.10.234:41610
#    depends_on:
#      - nsqlookupd
#    ports:
#      - "4171:4171"