version: "3"
services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181:2181'
        volumes:
            - ./zookeeper_data:/bitnami/zookeeper
        environment:
            - TZ=Asia/Shanghai
            - LANG=en_US.UTF-8
            - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
        image: 'bitnami/kafka:latest'
        ports:
            - "9092:9092"
        volumes:
          - ./kafka_data:/bitnami/kafka
        environment:
            - TZ=Asia/Shanghai
            - LANG=en_US.UTF-8
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
        depends_on:
            - zookeeper