version: '2'
services:
  elasticsearch:
    image: 'docker.io/bitnami/elasticsearch:7-debian-10'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - ./elasticsearch/data:/bitnami/elasticsearch/data
  kibana:
    image: 'docker.io/bitnami/kibana:7-debian-10'
    ports:
      - '5601:5601'
    volumes:
      - ./kibana/data:/bitnami/kibana/data
    depends_on:
      - elasticsearch
